name: Deploy to Private Server

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        clean: false  # Preserve data and logs directories

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create/update virtual environment
      run: |
        uv venv .venv --python python3
        source .venv/bin/activate
        uv pip install -r requirements.txt

    - name: Create necessary directories
      run: |
        mkdir -p data logs

    - name: Set permissions
      run: |
        chmod +x *.py

    - name: Deployment summary
      run: |
        source .venv/bin/activate
        echo "✅ Deployment successful!"
        echo "Working directory: $(pwd)"
        echo "Python version: $(python --version)"
        echo "uv version: $(uv --version)"
        echo "Installed packages:"
        uv pip list | grep -E "requests|sleeper"
