name: Deploy to Private Server

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        clean: false  # Preserve data and logs directories

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt --user

    - name: Create necessary directories
      run: |
        mkdir -p data logs

    - name: Set permissions
      run: |
        chmod +x *.py

    - name: Deployment summary
      run: |
        echo "✅ Deployment successful!"
        echo "Release: ${{ github.event.release.tag_name }}"
        echo "Working directory: $(pwd)"
        echo "Python version: $(python3 --version)"
        echo "Installed packages:"
        python3 -m pip list | grep -E "requests|sleeper"
